package com.tanjo3.runesandmasteries.view;

import java.awt.Component;
import java.awt.Font;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.LayoutStyle;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;

public class GUI extends JFrame {

    private final HashMap<String, JLabel> ferocity = new HashMap<>();
    private final HashMap<String, JLabel> cunning = new HashMap<>();
    private final HashMap<String, JLabel> resolve = new HashMap<>();

    /**
     * Creates the main form.
     */
    public GUI() {
        initComponents();

        for (Component c : pnlFerocity.getComponents()) {
            if (c instanceof JLabel) {
                ferocity.put(c.getName(), (JLabel) c);
            }
        }

        for (Component c : pnlCunning.getComponents()) {
            if (c instanceof JLabel) {
                cunning.put(c.getName(), (JLabel) c);
            }
        }

        for (Component c : pnlResolve.getComponents()) {
            if (c instanceof JLabel) {
                resolve.put(c.getName(), (JLabel) c);
            }
        }
    }

    /**
     * Resets the runes and masteries list as well as the output.
     */
    public void resetAll() {
        ((DefaultListModel) lstRunesInfo.getModel()).clear();
        resetRunes();

        ((DefaultListModel) lstMasteryInfo.getModel()).clear();
        resetMasteries();
    }

    /**
     * Blanks the field where the runes are listed.
     */
    public void resetRunes() {
        ((DefaultListModel) lstMarks.getModel()).clear();
        ((DefaultListModel) lstSeals.getModel()).clear();
        ((DefaultListModel) lstGlyphs.getModel()).clear();
        ((DefaultListModel) lstQuints.getModel()).clear();
    }

    /**
     * Resets all the masteries to 0. Should be called prior to updating
     * masteries.
     */
    public void resetMasteries() {
        ferocity.values().stream().forEach((label) -> {
            label.setText("0");
            label.setEnabled(false);
        });

        cunning.values().stream().forEach((label) -> {
            label.setText("0");
            label.setEnabled(false);
        });

        resolve.values().stream().forEach((label) -> {
            label.setText("0");
            label.setEnabled(false);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRunesInfo = new JScrollPane();
        lstRunesInfo = new JList<>();
        pnlRunes = new JPanel();
        lblMarkImg = new JLabel();
        pnlMarks = new JScrollPane();
        lstMarks = new JList<>();
        lblSealImg = new JLabel();
        pnlSeals = new JScrollPane();
        lstSeals = new JList<>();
        lblGlyphImg = new JLabel();
        pnlGlyphs = new JScrollPane();
        lstGlyphs = new JList<>();
        lblQuintImg = new JLabel();
        pnlQuints = new JScrollPane();
        lstQuints = new JList<>();
        pnlMasteryInfo = new JScrollPane();
        lstMasteryInfo = new JList<>();
        pnlMasteries = new JPanel();
        pnlFerocity = new JPanel();
        lbl6111 = new JLabel();
        lbl6114 = new JLabel();
        lbl6121 = new JLabel();
        lbl6122 = new JLabel();
        lbl6123 = new JLabel();
        lbl6131 = new JLabel();
        lbl6134 = new JLabel();
        lbl6141 = new JLabel();
        lbl6142 = new JLabel();
        lbl6143 = new JLabel();
        lbl6151 = new JLabel();
        lbl6154 = new JLabel();
        lbl6161 = new JLabel();
        lbl6162 = new JLabel();
        lbl6164 = new JLabel();
        pnlCunning = new JPanel();
        lbl6311 = new JLabel();
        lbl6312 = new JLabel();
        lbl6321 = new JLabel();
        lbl6322 = new JLabel();
        lbl6323 = new JLabel();
        lbl6331 = new JLabel();
        lbl6332 = new JLabel();
        lbl6341 = new JLabel();
        lbl6342 = new JLabel();
        lbl6343 = new JLabel();
        lbl6351 = new JLabel();
        lbl6352 = new JLabel();
        lbl6361 = new JLabel();
        lbl6362 = new JLabel();
        lbl6363 = new JLabel();
        pnlResolve = new JPanel();
        lbl6211 = new JLabel();
        lbl6212 = new JLabel();
        lbl6221 = new JLabel();
        lbl6223 = new JLabel();
        lbl6222 = new JLabel();
        lbl6231 = new JLabel();
        lbl6232 = new JLabel();
        lbl6241 = new JLabel();
        lbl6242 = new JLabel();
        lbl6243 = new JLabel();
        lbl6251 = new JLabel();
        lbl6252 = new JLabel();
        lbl6261 = new JLabel();
        lbl6262 = new JLabel();
        lbl6263 = new JLabel();
        vertSplit = new JSeparator();
        botSplit = new JSeparator();
        cmdNew = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoL Runes and Masteries");

        lstRunesInfo.setFont(new Font("Felix Titling", 0, 12)); // NOI18N
        lstRunesInfo.setModel(new DefaultListModel());
        lstRunesInfo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        pnlRunesInfo.setViewportView(lstRunesInfo);

        lblMarkImg.setIcon(new ImageIcon(getClass().getResource("/images/rune_mark.png"))); // NOI18N
        lblMarkImg.setToolTipText("Marks");

        lstMarks.setFont(new Font("Felix Titling", 0, 12)); // NOI18N
        lstMarks.setModel(new DefaultListModel());
        lstMarks.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        pnlMarks.setViewportView(lstMarks);

        lblSealImg.setIcon(new ImageIcon(getClass().getResource("/images/rune_seal.png"))); // NOI18N
        lblSealImg.setToolTipText("Seals");

        lstSeals.setFont(new Font("Felix Titling", 0, 12)); // NOI18N
        lstSeals.setModel(new DefaultListModel());
        lstSeals.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        pnlSeals.setViewportView(lstSeals);

        lblGlyphImg.setIcon(new ImageIcon(getClass().getResource("/images/rune_glyph.png"))); // NOI18N
        lblGlyphImg.setToolTipText("Glyphs");

        lstGlyphs.setFont(new Font("Felix Titling", 0, 12)); // NOI18N
        lstGlyphs.setModel(new DefaultListModel());
        lstGlyphs.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        pnlGlyphs.setViewportView(lstGlyphs);

        lblQuintImg.setIcon(new ImageIcon(getClass().getResource("/images/rune_quint.png"))); // NOI18N
        lblQuintImg.setToolTipText("Quintessences");

        lstQuints.setFont(new Font("Felix Titling", 0, 12)); // NOI18N
        lstQuints.setModel(new DefaultListModel());
        lstQuints.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        pnlQuints.setViewportView(lstQuints);

        GroupLayout pnlRunesLayout = new GroupLayout(pnlRunes);
        pnlRunes.setLayout(pnlRunesLayout);
        pnlRunesLayout.setHorizontalGroup(pnlRunesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRunesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRunesLayout.createSequentialGroup()
                        .addComponent(lblMarkImg)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMarks))
                    .addGroup(pnlRunesLayout.createSequentialGroup()
                        .addComponent(lblQuintImg)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlQuints, GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
                    .addGroup(pnlRunesLayout.createSequentialGroup()
                        .addComponent(lblSealImg)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSeals, GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
                    .addGroup(pnlRunesLayout.createSequentialGroup()
                        .addComponent(lblGlyphImg)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlGlyphs, GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlRunesLayout.setVerticalGroup(pnlRunesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlRunesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRunesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lblMarkImg)
                    .addComponent(pnlMarks, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlRunesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lblSealImg)
                    .addComponent(pnlSeals, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRunesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lblGlyphImg)
                    .addComponent(pnlGlyphs, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRunesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuintImg)
                    .addComponent(pnlQuints, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lstMasteryInfo.setFont(new Font("Felix Titling", 0, 12)); // NOI18N
        lstMasteryInfo.setModel(new DefaultListModel());
        lstMasteryInfo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        pnlMasteryInfo.setViewportView(lstMasteryInfo);

        pnlFerocity.setBorder(BorderFactory.createTitledBorder(null, "Ferocity", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Felix Titling", 1, 14))); // NOI18N

        lbl6111.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6111.setIcon(new ImageIcon(getClass().getResource("/images/6111.png"))); // NOI18N
        lbl6111.setText("0");
        lbl6111.setToolTipText("Fury");
        lbl6111.setEnabled(false);
        lbl6111.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6111.setName("6111"); // NOI18N
        lbl6111.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6114.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6114.setIcon(new ImageIcon(getClass().getResource("/images/6114.png"))); // NOI18N
        lbl6114.setText("0");
        lbl6114.setToolTipText("Sorcery");
        lbl6114.setEnabled(false);
        lbl6114.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6114.setName("6114"); // NOI18N
        lbl6114.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6121.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6121.setIcon(new ImageIcon(getClass().getResource("/images/6121.png"))); // NOI18N
        lbl6121.setText("0");
        lbl6121.setToolTipText("Fresh Blood");
        lbl6121.setEnabled(false);
        lbl6121.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6121.setName("6121"); // NOI18N
        lbl6121.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6122.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6122.setIcon(new ImageIcon(getClass().getResource("/images/6122.png"))); // NOI18N
        lbl6122.setText("0");
        lbl6122.setToolTipText("Feast");
        lbl6122.setEnabled(false);
        lbl6122.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6122.setName("6122"); // NOI18N
        lbl6122.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6123.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6123.setIcon(new ImageIcon(getClass().getResource("/images/6123.png"))); // NOI18N
        lbl6123.setText("0");
        lbl6123.setToolTipText("Expose Weakness");
        lbl6123.setEnabled(false);
        lbl6123.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6123.setName("6123"); // NOI18N
        lbl6123.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6131.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6131.setIcon(new ImageIcon(getClass().getResource("/images/6131.png"))); // NOI18N
        lbl6131.setText("0");
        lbl6131.setToolTipText("Vampirism");
        lbl6131.setEnabled(false);
        lbl6131.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6131.setName("6131"); // NOI18N
        lbl6131.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6134.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6134.setIcon(new ImageIcon(getClass().getResource("/images/6134.png"))); // NOI18N
        lbl6134.setText("0");
        lbl6134.setToolTipText("Natural Talent");
        lbl6134.setEnabled(false);
        lbl6134.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6134.setName("6134"); // NOI18N
        lbl6134.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6141.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6141.setIcon(new ImageIcon(getClass().getResource("/images/6141.png"))); // NOI18N
        lbl6141.setText("0");
        lbl6141.setToolTipText("Bounty Hunter");
        lbl6141.setEnabled(false);
        lbl6141.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6141.setName("6141"); // NOI18N
        lbl6141.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6142.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6142.setIcon(new ImageIcon(getClass().getResource("/images/6142.png"))); // NOI18N
        lbl6142.setText("0");
        lbl6142.setToolTipText("Double Edged Sword");
        lbl6142.setEnabled(false);
        lbl6142.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6142.setName("6142"); // NOI18N
        lbl6142.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6143.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6143.setIcon(new ImageIcon(getClass().getResource("/images/6143.png"))); // NOI18N
        lbl6143.setText("0");
        lbl6143.setToolTipText("Battle Trance");
        lbl6143.setEnabled(false);
        lbl6143.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6143.setName("6143"); // NOI18N
        lbl6143.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6151.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6151.setIcon(new ImageIcon(getClass().getResource("/images/6151.png"))); // NOI18N
        lbl6151.setText("0");
        lbl6151.setToolTipText("Battering Blows");
        lbl6151.setEnabled(false);
        lbl6151.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6151.setName("6151"); // NOI18N
        lbl6151.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6154.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6154.setIcon(new ImageIcon(getClass().getResource("/images/6154.png"))); // NOI18N
        lbl6154.setText("0");
        lbl6154.setToolTipText("Piercing Thoughts");
        lbl6154.setEnabled(false);
        lbl6154.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6154.setName("6154"); // NOI18N
        lbl6154.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6161.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6161.setIcon(new ImageIcon(getClass().getResource("/images/6161.png"))); // NOI18N
        lbl6161.setText("0");
        lbl6161.setToolTipText("Warlord's Bloodlust");
        lbl6161.setEnabled(false);
        lbl6161.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6161.setName("6161"); // NOI18N
        lbl6161.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6162.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6162.setIcon(new ImageIcon(getClass().getResource("/images/6162.png"))); // NOI18N
        lbl6162.setText("0");
        lbl6162.setToolTipText("Fervor of Battle");
        lbl6162.setEnabled(false);
        lbl6162.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6162.setName("6162"); // NOI18N
        lbl6162.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6164.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6164.setIcon(new ImageIcon(getClass().getResource("/images/6164.png"))); // NOI18N
        lbl6164.setText("0");
        lbl6164.setToolTipText("Deathfire Touch");
        lbl6164.setEnabled(false);
        lbl6164.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6164.setName("6164"); // NOI18N
        lbl6164.setVerticalTextPosition(SwingConstants.BOTTOM);

        GroupLayout pnlFerocityLayout = new GroupLayout(pnlFerocity);
        pnlFerocity.setLayout(pnlFerocityLayout);
        pnlFerocityLayout.setHorizontalGroup(pnlFerocityLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlFerocityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFerocityLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6131)
                    .addGroup(GroupLayout.Alignment.TRAILING, pnlFerocityLayout.createSequentialGroup()
                        .addComponent(lbl6151)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl6154))
                    .addGroup(pnlFerocityLayout.createSequentialGroup()
                        .addComponent(lbl6161)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl6162)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl6164))
                    .addGroup(pnlFerocityLayout.createSequentialGroup()
                        .addComponent(lbl6141)
                        .addGap(6, 6, 6)
                        .addComponent(lbl6142)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl6143))
                    .addGroup(pnlFerocityLayout.createSequentialGroup()
                        .addComponent(lbl6111)
                        .addGap(76, 76, 76)
                        .addComponent(lbl6114))
                    .addGroup(pnlFerocityLayout.createSequentialGroup()
                        .addComponent(lbl6121)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl6122)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFerocityLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(lbl6134)
                            .addComponent(lbl6123))))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFerocityLayout.setVerticalGroup(pnlFerocityLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlFerocityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFerocityLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6111)
                    .addComponent(lbl6114))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFerocityLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6121)
                    .addComponent(lbl6122)
                    .addComponent(lbl6123))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFerocityLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6131)
                    .addComponent(lbl6134))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFerocityLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6142)
                    .addComponent(lbl6141)
                    .addComponent(lbl6143))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFerocityLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6151)
                    .addComponent(lbl6154))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFerocityLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6162)
                    .addComponent(lbl6161)
                    .addComponent(lbl6164))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCunning.setBorder(BorderFactory.createTitledBorder(null, "Cunning", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Felix Titling", 1, 14))); // NOI18N

        lbl6311.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6311.setIcon(new ImageIcon(getClass().getResource("/images/6311.png"))); // NOI18N
        lbl6311.setText("0");
        lbl6311.setToolTipText("Wanderer");
        lbl6311.setEnabled(false);
        lbl6311.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6311.setName("6311"); // NOI18N
        lbl6311.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6312.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6312.setIcon(new ImageIcon(getClass().getResource("/images/6312.png"))); // NOI18N
        lbl6312.setText("0");
        lbl6312.setToolTipText("Savagery");
        lbl6312.setEnabled(false);
        lbl6312.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6312.setName("6312"); // NOI18N
        lbl6312.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6321.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6321.setIcon(new ImageIcon(getClass().getResource("/images/6321.png"))); // NOI18N
        lbl6321.setText("0");
        lbl6321.setToolTipText("Runic Affinity");
        lbl6321.setEnabled(false);
        lbl6321.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6321.setName("6321"); // NOI18N
        lbl6321.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6322.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6322.setIcon(new ImageIcon(getClass().getResource("/images/6322.png"))); // NOI18N
        lbl6322.setText("0");
        lbl6322.setToolTipText("Secret Stash");
        lbl6322.setEnabled(false);
        lbl6322.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6322.setName("6322"); // NOI18N
        lbl6322.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6323.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6323.setIcon(new ImageIcon(getClass().getResource("/images/6323.png"))); // NOI18N
        lbl6323.setText("0");
        lbl6323.setToolTipText("Assassin");
        lbl6323.setEnabled(false);
        lbl6323.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6323.setName("6323"); // NOI18N
        lbl6323.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6331.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6331.setIcon(new ImageIcon(getClass().getResource("/images/6331.png"))); // NOI18N
        lbl6331.setText("0");
        lbl6331.setToolTipText("Merciless");
        lbl6331.setEnabled(false);
        lbl6331.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6331.setName("6331"); // NOI18N
        lbl6331.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6332.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6332.setIcon(new ImageIcon(getClass().getResource("/images/6332.png"))); // NOI18N
        lbl6332.setText("0");
        lbl6332.setToolTipText("Meditation");
        lbl6332.setEnabled(false);
        lbl6332.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6332.setName("6332"); // NOI18N
        lbl6332.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6341.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6341.setIcon(new ImageIcon(getClass().getResource("/images/6341.png"))); // NOI18N
        lbl6341.setText("0");
        lbl6341.setToolTipText("Greenfather's Gift");
        lbl6341.setEnabled(false);
        lbl6341.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6341.setName("6341"); // NOI18N
        lbl6341.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6342.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6342.setIcon(new ImageIcon(getClass().getResource("/images/6342.png"))); // NOI18N
        lbl6342.setText("0");
        lbl6342.setToolTipText("Bandit");
        lbl6342.setEnabled(false);
        lbl6342.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6342.setName("6342"); // NOI18N
        lbl6342.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6343.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6343.setIcon(new ImageIcon(getClass().getResource("/images/6343.png"))); // NOI18N
        lbl6343.setText("0");
        lbl6343.setToolTipText("Dangerous Game");
        lbl6343.setEnabled(false);
        lbl6343.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6343.setName("6343"); // NOI18N
        lbl6343.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6351.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6351.setIcon(new ImageIcon(getClass().getResource("/images/6351.png"))); // NOI18N
        lbl6351.setText("0");
        lbl6351.setToolTipText("Precision");
        lbl6351.setEnabled(false);
        lbl6351.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6351.setName("6351"); // NOI18N
        lbl6351.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6352.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6352.setIcon(new ImageIcon(getClass().getResource("/images/6352.png"))); // NOI18N
        lbl6352.setText("0");
        lbl6352.setToolTipText("Intelligence");
        lbl6352.setEnabled(false);
        lbl6352.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6352.setName("6352"); // NOI18N
        lbl6352.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6361.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6361.setIcon(new ImageIcon(getClass().getResource("/images/6361.png"))); // NOI18N
        lbl6361.setText("0");
        lbl6361.setToolTipText("Stormraider's Surge");
        lbl6361.setEnabled(false);
        lbl6361.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6361.setName("6361"); // NOI18N
        lbl6361.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6362.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6362.setIcon(new ImageIcon(getClass().getResource("/images/6362.png"))); // NOI18N
        lbl6362.setText("0");
        lbl6362.setToolTipText("Thunderlord's Decree");
        lbl6362.setEnabled(false);
        lbl6362.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6362.setName("6362"); // NOI18N
        lbl6362.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6363.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6363.setHorizontalAlignment(SwingConstants.CENTER);
        lbl6363.setIcon(new ImageIcon(getClass().getResource("/images/6363.png"))); // NOI18N
        lbl6363.setText("0");
        lbl6363.setToolTipText("Windspeaker's Blessing");
        lbl6363.setEnabled(false);
        lbl6363.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6363.setName("6363"); // NOI18N
        lbl6363.setVerticalTextPosition(SwingConstants.BOTTOM);

        GroupLayout pnlCunningLayout = new GroupLayout(pnlCunning);
        pnlCunning.setLayout(pnlCunningLayout);
        pnlCunningLayout.setHorizontalGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlCunningLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCunningLayout.createSequentialGroup()
                        .addComponent(lbl6331)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCunningLayout.createSequentialGroup()
                        .addGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.TRAILING, pnlCunningLayout.createSequentialGroup()
                                .addComponent(lbl6351)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl6352))
                            .addGroup(pnlCunningLayout.createSequentialGroup()
                                .addGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlCunningLayout.createSequentialGroup()
                                        .addComponent(lbl6361)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl6362)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl6363))
                                    .addGroup(pnlCunningLayout.createSequentialGroup()
                                        .addComponent(lbl6341)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl6342)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl6343))
                                    .addGroup(pnlCunningLayout.createSequentialGroup()
                                        .addGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlCunningLayout.createSequentialGroup()
                                                .addComponent(lbl6321)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl6322))
                                            .addComponent(lbl6311))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl6312)
                                            .addComponent(lbl6332)
                                            .addComponent(lbl6323))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        pnlCunningLayout.setVerticalGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, pnlCunningLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6312)
                    .addComponent(lbl6311))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6323)
                    .addComponent(lbl6322)
                    .addComponent(lbl6321))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6332)
                    .addComponent(lbl6331))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6343)
                    .addComponent(lbl6341)
                    .addComponent(lbl6342))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6352)
                    .addComponent(lbl6351))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCunningLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6363)
                    .addComponent(lbl6362)
                    .addComponent(lbl6361))
                .addContainerGap())
        );

        pnlResolve.setBorder(BorderFactory.createTitledBorder(null, "Resolve", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Felix Titling", 1, 14))); // NOI18N

        lbl6211.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6211.setIcon(new ImageIcon(getClass().getResource("/images/6211.png"))); // NOI18N
        lbl6211.setText("0");
        lbl6211.setToolTipText("Recovery");
        lbl6211.setEnabled(false);
        lbl6211.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6211.setName("6211"); // NOI18N
        lbl6211.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6212.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6212.setIcon(new ImageIcon(getClass().getResource("/images/6212.png"))); // NOI18N
        lbl6212.setText("0");
        lbl6212.setToolTipText("Unyielding");
        lbl6212.setEnabled(false);
        lbl6212.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6212.setName("6212"); // NOI18N
        lbl6212.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6221.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6221.setIcon(new ImageIcon(getClass().getResource("/images/6221.png"))); // NOI18N
        lbl6221.setText("0");
        lbl6221.setToolTipText("Explorer");
        lbl6221.setEnabled(false);
        lbl6221.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6221.setName("6221"); // NOI18N
        lbl6221.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6223.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6223.setIcon(new ImageIcon(getClass().getResource("/images/6223.png"))); // NOI18N
        lbl6223.setText("0");
        lbl6223.setToolTipText("Tough Skin");
        lbl6223.setEnabled(false);
        lbl6223.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6223.setName("6223"); // NOI18N
        lbl6223.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6222.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6222.setIcon(new ImageIcon(getClass().getResource("/images/6222.png"))); // NOI18N
        lbl6222.setText("0");
        lbl6222.setToolTipText("Siegemaster");
        lbl6222.setEnabled(false);
        lbl6222.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6222.setName("6222"); // NOI18N
        lbl6222.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6231.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6231.setIcon(new ImageIcon(getClass().getResource("/images/6231.png"))); // NOI18N
        lbl6231.setText("0");
        lbl6231.setToolTipText("Runic Armor");
        lbl6231.setEnabled(false);
        lbl6231.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6231.setName("6231"); // NOI18N
        lbl6231.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6232.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6232.setIcon(new ImageIcon(getClass().getResource("/images/6232.png"))); // NOI18N
        lbl6232.setText("0");
        lbl6232.setToolTipText("Veteran's Scars");
        lbl6232.setEnabled(false);
        lbl6232.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6232.setName("6232"); // NOI18N
        lbl6232.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6241.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6241.setIcon(new ImageIcon(getClass().getResource("/images/6241.png"))); // NOI18N
        lbl6241.setText("0");
        lbl6241.setToolTipText("Insight");
        lbl6241.setEnabled(false);
        lbl6241.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6241.setName("6241"); // NOI18N
        lbl6241.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6242.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6242.setIcon(new ImageIcon(getClass().getResource("/images/6242.png"))); // NOI18N
        lbl6242.setText("0");
        lbl6242.setToolTipText("Perseverance");
        lbl6242.setEnabled(false);
        lbl6242.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6242.setName("6242"); // NOI18N
        lbl6242.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6243.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6243.setIcon(new ImageIcon(getClass().getResource("/images/6243.png"))); // NOI18N
        lbl6243.setText("0");
        lbl6243.setToolTipText("Fearless");
        lbl6243.setEnabled(false);
        lbl6243.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6243.setName("6243"); // NOI18N
        lbl6243.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6251.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6251.setIcon(new ImageIcon(getClass().getResource("/images/6251.png"))); // NOI18N
        lbl6251.setText("0");
        lbl6251.setToolTipText("Swiftness");
        lbl6251.setEnabled(false);
        lbl6251.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6251.setName("6251"); // NOI18N
        lbl6251.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6252.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6252.setIcon(new ImageIcon(getClass().getResource("/images/6252.png"))); // NOI18N
        lbl6252.setText("0");
        lbl6252.setToolTipText("Legendary Guardian");
        lbl6252.setEnabled(false);
        lbl6252.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6252.setName("6252"); // NOI18N
        lbl6252.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6261.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6261.setIcon(new ImageIcon(getClass().getResource("/images/6261.png"))); // NOI18N
        lbl6261.setText("0");
        lbl6261.setToolTipText("Grasp of the Undying");
        lbl6261.setEnabled(false);
        lbl6261.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6261.setName("6261"); // NOI18N
        lbl6261.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6262.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6262.setIcon(new ImageIcon(getClass().getResource("/images/6262.png"))); // NOI18N
        lbl6262.setText("0");
        lbl6262.setToolTipText("Courage of the Colossus");
        lbl6262.setEnabled(false);
        lbl6262.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6262.setName("6262"); // NOI18N
        lbl6262.setVerticalTextPosition(SwingConstants.BOTTOM);

        lbl6263.setFont(new Font("Felix Titling", 1, 14)); // NOI18N
        lbl6263.setIcon(new ImageIcon(getClass().getResource("/images/6263.png"))); // NOI18N
        lbl6263.setText("0");
        lbl6263.setToolTipText("Bond of Stone");
        lbl6263.setEnabled(false);
        lbl6263.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl6263.setName("6263"); // NOI18N
        lbl6263.setVerticalTextPosition(SwingConstants.BOTTOM);

        GroupLayout pnlResolveLayout = new GroupLayout(pnlResolve);
        pnlResolve.setLayout(pnlResolveLayout);
        pnlResolveLayout.setHorizontalGroup(pnlResolveLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlResolveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResolveLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnlResolveLayout.createSequentialGroup()
                        .addComponent(lbl6211)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl6212))
                    .addGroup(pnlResolveLayout.createSequentialGroup()
                        .addGroup(pnlResolveLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlResolveLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(GroupLayout.Alignment.TRAILING, pnlResolveLayout.createSequentialGroup()
                                    .addComponent(lbl6231)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl6232))
                                .addGroup(pnlResolveLayout.createSequentialGroup()
                                    .addComponent(lbl6251)
                                    .addGap(76, 76, 76)
                                    .addComponent(lbl6252)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(pnlResolveLayout.createSequentialGroup()
                                .addComponent(lbl6221)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl6223)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl6222))
                            .addGroup(pnlResolveLayout.createSequentialGroup()
                                .addComponent(lbl6241)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl6242)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl6243))
                            .addGroup(pnlResolveLayout.createSequentialGroup()
                                .addComponent(lbl6261)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl6262)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl6263)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlResolveLayout.setVerticalGroup(pnlResolveLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlResolveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResolveLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6212)
                    .addComponent(lbl6211))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResolveLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6223)
                    .addComponent(lbl6221)
                    .addComponent(lbl6222))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResolveLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6232)
                    .addComponent(lbl6231))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResolveLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6242)
                    .addComponent(lbl6241)
                    .addComponent(lbl6243))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlResolveLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6251)
                    .addComponent(lbl6252))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResolveLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(lbl6263)
                    .addComponent(lbl6261)
                    .addComponent(lbl6262))
                .addContainerGap())
        );

        GroupLayout pnlMasteriesLayout = new GroupLayout(pnlMasteries);
        pnlMasteries.setLayout(pnlMasteriesLayout);
        pnlMasteriesLayout.setHorizontalGroup(pnlMasteriesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlMasteriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFerocity, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCunning, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResolve, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMasteriesLayout.setVerticalGroup(pnlMasteriesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlMasteriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMasteriesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(pnlResolve, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFerocity, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCunning, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        vertSplit.setOrientation(SwingConstants.VERTICAL);

        cmdNew.setFont(new Font("Felix Titling", 0, 12)); // NOI18N
        cmdNew.setText("New Query");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRunesInfo, GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                    .addComponent(cmdNew, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botSplit)
                    .addComponent(pnlRunes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vertSplit, GroupLayout.PREFERRED_SIZE, 2, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMasteries, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMasteryInfo))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(vertSplit)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pnlRunesInfo, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlRunes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botSplit, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdNew, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pnlMasteryInfo)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMasteries, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getNewQueryButton() {
        return cmdNew;
    }

    public JList<String> getRunesList() {
        return lstRunesInfo;
    }

    public JList<String> getMasteriesList() {
        return lstMasteryInfo;
    }

    public JList<String> getMarksList() {
        return lstMarks;
    }

    public JList<String> getSealsList() {
        return lstSeals;
    }

    public JList<String> getGlyphsList() {
        return lstGlyphs;
    }

    public JList<String> getQuintsList() {
        return lstQuints;
    }

    public HashMap<String, JLabel> getFerocityTree() {
        return ferocity;
    }

    public HashMap<String, JLabel> getCunningTree() {
        return cunning;
    }

    public HashMap<String, JLabel> getResolveTree() {
        return resolve;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JSeparator botSplit;
    private JButton cmdNew;
    private JLabel lbl6111;
    private JLabel lbl6114;
    private JLabel lbl6121;
    private JLabel lbl6122;
    private JLabel lbl6123;
    private JLabel lbl6131;
    private JLabel lbl6134;
    private JLabel lbl6141;
    private JLabel lbl6142;
    private JLabel lbl6143;
    private JLabel lbl6151;
    private JLabel lbl6154;
    private JLabel lbl6161;
    private JLabel lbl6162;
    private JLabel lbl6164;
    private JLabel lbl6211;
    private JLabel lbl6212;
    private JLabel lbl6221;
    private JLabel lbl6222;
    private JLabel lbl6223;
    private JLabel lbl6231;
    private JLabel lbl6232;
    private JLabel lbl6241;
    private JLabel lbl6242;
    private JLabel lbl6243;
    private JLabel lbl6251;
    private JLabel lbl6252;
    private JLabel lbl6261;
    private JLabel lbl6262;
    private JLabel lbl6263;
    private JLabel lbl6311;
    private JLabel lbl6312;
    private JLabel lbl6321;
    private JLabel lbl6322;
    private JLabel lbl6323;
    private JLabel lbl6331;
    private JLabel lbl6332;
    private JLabel lbl6341;
    private JLabel lbl6342;
    private JLabel lbl6343;
    private JLabel lbl6351;
    private JLabel lbl6352;
    private JLabel lbl6361;
    private JLabel lbl6362;
    private JLabel lbl6363;
    private JLabel lblGlyphImg;
    private JLabel lblMarkImg;
    private JLabel lblQuintImg;
    private JLabel lblSealImg;
    private JList<String> lstGlyphs;
    private JList<String> lstMarks;
    private JList<String> lstMasteryInfo;
    private JList<String> lstQuints;
    private JList<String> lstRunesInfo;
    private JList<String> lstSeals;
    private JPanel pnlCunning;
    private JPanel pnlFerocity;
    private JScrollPane pnlGlyphs;
    private JScrollPane pnlMarks;
    private JPanel pnlMasteries;
    private JScrollPane pnlMasteryInfo;
    private JScrollPane pnlQuints;
    private JPanel pnlResolve;
    private JPanel pnlRunes;
    private JScrollPane pnlRunesInfo;
    private JScrollPane pnlSeals;
    private JSeparator vertSplit;
    // End of variables declaration//GEN-END:variables
}
